name: Bug Report
description: 不具合の報告用テンプレート
title: "[Bug]: "
labels:
  - bug
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        不具合の詳細について記入してください。

  - type: input
    id: summary
    attributes:
      label: 概要
      description: 発生している問題の要点を簡潔に記述してください。
      placeholder: 例）アプリ起動時にクラッシュする
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: 再現手順
      description: バグを再現するための手順を記載してください。
      placeholder: |
        1. …
        2. …
        3. …
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: 期待される動作
      placeholder: 本来期待される動作を記述してください。
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: 実際の動作
      placeholder: バグ発生時の動作を記述してください。
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: 実行環境
      description: 発生環境の詳細を記載してください。
      placeholder: OS / バージョン / 使用ブラウザ / ランタイム / ライブラリバージョン等
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: ログ
      description: エラーメッセージやログがあれば貼り付けてください。
      render: bash
    validations:
      required: false
